#!/bin/sh
OBJDUMP=objdump
PREFIX=aarch64-linux-gnu-

ARM64OBJDUMP=`which $PREFIX$OBJDUMP`
HOSTOBJDUMP=`which $OBJDUMP`

ACTUALOBJDUMP=""

# Prefer AArch64 objdump
if [ "$ARM64OBJDUMP" = "" ]; then
	if [ "$HOSTOBJDUMP" != "" ]; then
	  ACTUALOBJDUMP=$HOSTOBJDUMP
	fi
else
	ACTUALOBJDUMP=$ARM64OBJDUMP
fi

if [ "$ACTUALOBJDUMP" = "" ]; then
	echo "No Objdump found!"
	exit
fi
 
if [ "$1" = "" ]; then
	echo "$0 <Sourcefile>"
else
	sourcefile=`basename -s .elf $1`
	$ACTUALOBJDUMP -rdj .text -j .data -j .bss $sourcefile.elf > $sourcefile.objdump
fi

