#!/bin/sh
OBJDUMP=objdump
PREFIX=aarch64-gnu-linux-

ARM64OBJDUMP=`which $PREFIX$OBJDUMP`
HOSTOBJDUMP=`which $OBJDUMP`

ACTUALOBJDUMP=""

# Prefer AArch64 objdump
if [ x$ARM64OBJDUMP == "x" ]; then
	if [ x$HOSTOBJDUMP != "x" ]; then
	  ACTUALOBJDUMP=$HOSTOBJDUMP
	fi
else
	ACTUALOBJDUMP=$ARM64OBJDUMP
fi

if [ x$ACTUALOBJDUMP == "x" ]; then
	echo "No Objdump found!"
	exit
fi
 
if [ x$1 == "x" ]; then
	echo "$0 <Sourcefile>"
else
	sourcefile=`basename -s .elf $1`
	$OBJDUMP -rdj .text -j .data -j .bss $sourcefile.elf > $sourcefile.objdump
fi

